#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x3A6A4DB839EAA6D7 (aacid@kde.org)
#
Name     : compat-poppler-soname123
Version  : 22.08.0
Release  : 2
URL      : https://poppler.freedesktop.org/poppler-22.08.0.tar.xz
Source0  : https://poppler.freedesktop.org/poppler-22.08.0.tar.xz
Source1  : https://poppler.freedesktop.org/poppler-22.08.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 GPL-3.0
Requires: compat-poppler-soname123-lib = %{version}-%{release}
Requires: compat-poppler-soname123-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : curl-dev
BuildRequires : freetype-dev
BuildRequires : glibc-bin
BuildRequires : glibc-dev
BuildRequires : gtk-doc-data
BuildRequires : libjpeg-turbo-dev
BuildRequires : libpng-dev
BuildRequires : openjpeg
BuildRequires : pkg-config
BuildRequires : pkgconfig(cairo-pdf)
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gobject-introspection-1.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(lcms2)
BuildRequires : pkgconfig(nss)
BuildRequires : python3
BuildRequires : qtbase-dev
BuildRequires : qtbase-extras
BuildRequires : tiff-dev
BuildRequires : zlib-dev

%description
Poppler, a PDF rendering library
================================
This is Poppler, a library for rendering PDF files, and examining or
modifying their structure.  Poppler originally came from the XPDF

%package lib
Summary: lib components for the compat-poppler-soname123 package.
Group: Libraries
Requires: compat-poppler-soname123-license = %{version}-%{release}

%description lib
lib components for the compat-poppler-soname123 package.


%package license
Summary: license components for the compat-poppler-soname123 package.
Group: Default

%description license
license components for the compat-poppler-soname123 package.


%prep
%setup -q -n poppler-22.08.0
cd %{_builddir}/poppler-22.08.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1662055408
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake .. -DENABLE_UNSTABLE_API_ABI_HEADERS=ON \
-DENABLE_UTILS=ON \
-DENABLE_LIBOPENJPEG=none
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1662055408
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-poppler-soname123
cp %{_builddir}/poppler-%{version}/COPYING %{buildroot}/usr/share/package-licenses/compat-poppler-soname123/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
cp %{_builddir}/poppler-%{version}/COPYING3 %{buildroot}/usr/share/package-licenses/compat-poppler-soname123/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/poppler-%{version}/cmake/modules/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/compat-poppler-soname123/ff3ed70db4739b3c6747c7f624fe2bad70802987
pushd clr-build
%make_install
popd
## Remove excluded files
rm -f %{buildroot}*/usr/bin/pdfattach
rm -f %{buildroot}*/usr/bin/pdfdetach
rm -f %{buildroot}*/usr/bin/pdffonts
rm -f %{buildroot}*/usr/bin/pdfimages
rm -f %{buildroot}*/usr/bin/pdfinfo
rm -f %{buildroot}*/usr/bin/pdfseparate
rm -f %{buildroot}*/usr/bin/pdfsig
rm -f %{buildroot}*/usr/bin/pdftocairo
rm -f %{buildroot}*/usr/bin/pdftohtml
rm -f %{buildroot}*/usr/bin/pdftoppm
rm -f %{buildroot}*/usr/bin/pdftops
rm -f %{buildroot}*/usr/bin/pdftotext
rm -f %{buildroot}*/usr/bin/pdfunite
rm -f %{buildroot}*/usr/include/poppler/Annot.h
rm -f %{buildroot}*/usr/include/poppler/AnnotStampImageHelper.h
rm -f %{buildroot}*/usr/include/poppler/Array.h
rm -f %{buildroot}*/usr/include/poppler/BBoxOutputDev.h
rm -f %{buildroot}*/usr/include/poppler/CMap.h
rm -f %{buildroot}*/usr/include/poppler/CachedFile.h
rm -f %{buildroot}*/usr/include/poppler/CairoFontEngine.h
rm -f %{buildroot}*/usr/include/poppler/CairoOutputDev.h
rm -f %{buildroot}*/usr/include/poppler/CairoRescaleBox.h
rm -f %{buildroot}*/usr/include/poppler/Catalog.h
rm -f %{buildroot}*/usr/include/poppler/CertificateInfo.h
rm -f %{buildroot}*/usr/include/poppler/CharCodeToUnicode.h
rm -f %{buildroot}*/usr/include/poppler/CharTypes.h
rm -f %{buildroot}*/usr/include/poppler/CurlCachedFile.h
rm -f %{buildroot}*/usr/include/poppler/CurlPDFDocBuilder.h
rm -f %{buildroot}*/usr/include/poppler/DateInfo.h
rm -f %{buildroot}*/usr/include/poppler/Decrypt.h
rm -f %{buildroot}*/usr/include/poppler/Dict.h
rm -f %{buildroot}*/usr/include/poppler/Error.h
rm -f %{buildroot}*/usr/include/poppler/ErrorCodes.h
rm -f %{buildroot}*/usr/include/poppler/FDPDFDocBuilder.h
rm -f %{buildroot}*/usr/include/poppler/FILECacheLoader.h
rm -f %{buildroot}*/usr/include/poppler/FileSpec.h
rm -f %{buildroot}*/usr/include/poppler/FontEncodingTables.h
rm -f %{buildroot}*/usr/include/poppler/FontInfo.h
rm -f %{buildroot}*/usr/include/poppler/Form.h
rm -f %{buildroot}*/usr/include/poppler/Function.h
rm -f %{buildroot}*/usr/include/poppler/Gfx.h
rm -f %{buildroot}*/usr/include/poppler/GfxFont.h
rm -f %{buildroot}*/usr/include/poppler/GfxState.h
rm -f %{buildroot}*/usr/include/poppler/GfxState_helpers.h
rm -f %{buildroot}*/usr/include/poppler/GlobalParams.h
rm -f %{buildroot}*/usr/include/poppler/Hints.h
rm -f %{buildroot}*/usr/include/poppler/JArithmeticDecoder.h
rm -f %{buildroot}*/usr/include/poppler/JBIG2Stream.h
rm -f %{buildroot}*/usr/include/poppler/JPXStream.h
rm -f %{buildroot}*/usr/include/poppler/JSInfo.h
rm -f %{buildroot}*/usr/include/poppler/Lexer.h
rm -f %{buildroot}*/usr/include/poppler/Linearization.h
rm -f %{buildroot}*/usr/include/poppler/Link.h
rm -f %{buildroot}*/usr/include/poppler/LocalPDFDocBuilder.h
rm -f %{buildroot}*/usr/include/poppler/MarkedContentOutputDev.h
rm -f %{buildroot}*/usr/include/poppler/Movie.h
rm -f %{buildroot}*/usr/include/poppler/NameToCharCode.h
rm -f %{buildroot}*/usr/include/poppler/NameToUnicodeTable.h
rm -f %{buildroot}*/usr/include/poppler/Object.h
rm -f %{buildroot}*/usr/include/poppler/OptionalContent.h
rm -f %{buildroot}*/usr/include/poppler/Outline.h
rm -f %{buildroot}*/usr/include/poppler/OutputDev.h
rm -f %{buildroot}*/usr/include/poppler/PDFDoc.h
rm -f %{buildroot}*/usr/include/poppler/PDFDocBuilder.h
rm -f %{buildroot}*/usr/include/poppler/PDFDocEncoding.h
rm -f %{buildroot}*/usr/include/poppler/PDFDocFactory.h
rm -f %{buildroot}*/usr/include/poppler/PSOutputDev.h
rm -f %{buildroot}*/usr/include/poppler/PSTokenizer.h
rm -f %{buildroot}*/usr/include/poppler/Page.h
rm -f %{buildroot}*/usr/include/poppler/PageTransition.h
rm -f %{buildroot}*/usr/include/poppler/Parser.h
rm -f %{buildroot}*/usr/include/poppler/PopplerCache.h
rm -f %{buildroot}*/usr/include/poppler/PreScanOutputDev.h
rm -f %{buildroot}*/usr/include/poppler/ProfileData.h
rm -f %{buildroot}*/usr/include/poppler/Rendition.h
rm -f %{buildroot}*/usr/include/poppler/SecurityHandler.h
rm -f %{buildroot}*/usr/include/poppler/Sound.h
rm -f %{buildroot}*/usr/include/poppler/SplashOutputDev.h
rm -f %{buildroot}*/usr/include/poppler/Stream-CCITT.h
rm -f %{buildroot}*/usr/include/poppler/Stream.h
rm -f %{buildroot}*/usr/include/poppler/StructElement.h
rm -f %{buildroot}*/usr/include/poppler/StructTreeRoot.h
rm -f %{buildroot}*/usr/include/poppler/TextOutputDev.h
rm -f %{buildroot}*/usr/include/poppler/UTF.h
rm -f %{buildroot}*/usr/include/poppler/UnicodeCClassTables.h
rm -f %{buildroot}*/usr/include/poppler/UnicodeCompTables.h
rm -f %{buildroot}*/usr/include/poppler/UnicodeDecompTables.h
rm -f %{buildroot}*/usr/include/poppler/UnicodeMap.h
rm -f %{buildroot}*/usr/include/poppler/UnicodeMapFuncs.h
rm -f %{buildroot}*/usr/include/poppler/UnicodeMapTables.h
rm -f %{buildroot}*/usr/include/poppler/UnicodeTypeTable.h
rm -f %{buildroot}*/usr/include/poppler/ViewerPreferences.h
rm -f %{buildroot}*/usr/include/poppler/XRef.h
rm -f %{buildroot}*/usr/include/poppler/cpp/poppler-destination.h
rm -f %{buildroot}*/usr/include/poppler/cpp/poppler-document.h
rm -f %{buildroot}*/usr/include/poppler/cpp/poppler-embedded-file.h
rm -f %{buildroot}*/usr/include/poppler/cpp/poppler-font-private.h
rm -f %{buildroot}*/usr/include/poppler/cpp/poppler-font.h
rm -f %{buildroot}*/usr/include/poppler/cpp/poppler-global.h
rm -f %{buildroot}*/usr/include/poppler/cpp/poppler-image.h
rm -f %{buildroot}*/usr/include/poppler/cpp/poppler-page-renderer.h
rm -f %{buildroot}*/usr/include/poppler/cpp/poppler-page-transition.h
rm -f %{buildroot}*/usr/include/poppler/cpp/poppler-page.h
rm -f %{buildroot}*/usr/include/poppler/cpp/poppler-rectangle.h
rm -f %{buildroot}*/usr/include/poppler/cpp/poppler-toc.h
rm -f %{buildroot}*/usr/include/poppler/cpp/poppler-version.h
rm -f %{buildroot}*/usr/include/poppler/cpp/poppler_cpp_export.h
rm -f %{buildroot}*/usr/include/poppler/fofi/FoFiBase.h
rm -f %{buildroot}*/usr/include/poppler/fofi/FoFiEncodings.h
rm -f %{buildroot}*/usr/include/poppler/fofi/FoFiIdentifier.h
rm -f %{buildroot}*/usr/include/poppler/fofi/FoFiTrueType.h
rm -f %{buildroot}*/usr/include/poppler/fofi/FoFiType1.h
rm -f %{buildroot}*/usr/include/poppler/fofi/FoFiType1C.h
rm -f %{buildroot}*/usr/include/poppler/glib/poppler-action.h
rm -f %{buildroot}*/usr/include/poppler/glib/poppler-annot.h
rm -f %{buildroot}*/usr/include/poppler/glib/poppler-attachment.h
rm -f %{buildroot}*/usr/include/poppler/glib/poppler-date.h
rm -f %{buildroot}*/usr/include/poppler/glib/poppler-document.h
rm -f %{buildroot}*/usr/include/poppler/glib/poppler-enums.h
rm -f %{buildroot}*/usr/include/poppler/glib/poppler-features.h
rm -f %{buildroot}*/usr/include/poppler/glib/poppler-form-field.h
rm -f %{buildroot}*/usr/include/poppler/glib/poppler-layer.h
rm -f %{buildroot}*/usr/include/poppler/glib/poppler-macros.h
rm -f %{buildroot}*/usr/include/poppler/glib/poppler-media.h
rm -f %{buildroot}*/usr/include/poppler/glib/poppler-movie.h
rm -f %{buildroot}*/usr/include/poppler/glib/poppler-page.h
rm -f %{buildroot}*/usr/include/poppler/glib/poppler-structure-element.h
rm -f %{buildroot}*/usr/include/poppler/glib/poppler.h
rm -f %{buildroot}*/usr/include/poppler/goo/GooCheckedOps.h
rm -f %{buildroot}*/usr/include/poppler/goo/GooLikely.h
rm -f %{buildroot}*/usr/include/poppler/goo/GooString.h
rm -f %{buildroot}*/usr/include/poppler/goo/GooTimer.h
rm -f %{buildroot}*/usr/include/poppler/goo/ImgWriter.h
rm -f %{buildroot}*/usr/include/poppler/goo/JpegWriter.h
rm -f %{buildroot}*/usr/include/poppler/goo/PNGWriter.h
rm -f %{buildroot}*/usr/include/poppler/goo/TiffWriter.h
rm -f %{buildroot}*/usr/include/poppler/goo/gdir.h
rm -f %{buildroot}*/usr/include/poppler/goo/gfile.h
rm -f %{buildroot}*/usr/include/poppler/goo/gmem.h
rm -f %{buildroot}*/usr/include/poppler/goo/grandom.h
rm -f %{buildroot}*/usr/include/poppler/goo/gstrtod.h
rm -f %{buildroot}*/usr/include/poppler/poppler-config.h
rm -f %{buildroot}*/usr/include/poppler/poppler_private_export.h
rm -f %{buildroot}*/usr/include/poppler/qt5/poppler-annotation.h
rm -f %{buildroot}*/usr/include/poppler/qt5/poppler-export.h
rm -f %{buildroot}*/usr/include/poppler/qt5/poppler-form.h
rm -f %{buildroot}*/usr/include/poppler/qt5/poppler-link.h
rm -f %{buildroot}*/usr/include/poppler/qt5/poppler-media.h
rm -f %{buildroot}*/usr/include/poppler/qt5/poppler-optcontent.h
rm -f %{buildroot}*/usr/include/poppler/qt5/poppler-page-transition.h
rm -f %{buildroot}*/usr/include/poppler/qt5/poppler-qt5.h
rm -f %{buildroot}*/usr/include/poppler/qt5/poppler-version.h
rm -f %{buildroot}*/usr/include/poppler/splash/Splash.h
rm -f %{buildroot}*/usr/include/poppler/splash/SplashBitmap.h
rm -f %{buildroot}*/usr/include/poppler/splash/SplashClip.h
rm -f %{buildroot}*/usr/include/poppler/splash/SplashErrorCodes.h
rm -f %{buildroot}*/usr/include/poppler/splash/SplashFTFont.h
rm -f %{buildroot}*/usr/include/poppler/splash/SplashFTFontEngine.h
rm -f %{buildroot}*/usr/include/poppler/splash/SplashFTFontFile.h
rm -f %{buildroot}*/usr/include/poppler/splash/SplashFont.h
rm -f %{buildroot}*/usr/include/poppler/splash/SplashFontEngine.h
rm -f %{buildroot}*/usr/include/poppler/splash/SplashFontFile.h
rm -f %{buildroot}*/usr/include/poppler/splash/SplashFontFileID.h
rm -f %{buildroot}*/usr/include/poppler/splash/SplashGlyphBitmap.h
rm -f %{buildroot}*/usr/include/poppler/splash/SplashMath.h
rm -f %{buildroot}*/usr/include/poppler/splash/SplashPath.h
rm -f %{buildroot}*/usr/include/poppler/splash/SplashPattern.h
rm -f %{buildroot}*/usr/include/poppler/splash/SplashScreen.h
rm -f %{buildroot}*/usr/include/poppler/splash/SplashState.h
rm -f %{buildroot}*/usr/include/poppler/splash/SplashTypes.h
rm -f %{buildroot}*/usr/include/poppler/splash/SplashXPath.h
rm -f %{buildroot}*/usr/include/poppler/splash/SplashXPathScanner.h
rm -f %{buildroot}*/usr/lib64/girepository-1.0/Poppler-0.18.typelib
rm -f %{buildroot}*/usr/lib64/libpoppler.so
rm -f %{buildroot}*/usr/lib64/pkgconfig/poppler-cpp.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/poppler-glib.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/poppler-qt5.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/poppler.pc
rm -f %{buildroot}*/usr/share/gir-1.0/Poppler-0.18.gir
rm -f %{buildroot}*/usr/share/man/man1/pdfattach.1
rm -f %{buildroot}*/usr/share/man/man1/pdfdetach.1
rm -f %{buildroot}*/usr/share/man/man1/pdffonts.1
rm -f %{buildroot}*/usr/share/man/man1/pdfimages.1
rm -f %{buildroot}*/usr/share/man/man1/pdfinfo.1
rm -f %{buildroot}*/usr/share/man/man1/pdfseparate.1
rm -f %{buildroot}*/usr/share/man/man1/pdfsig.1
rm -f %{buildroot}*/usr/share/man/man1/pdftocairo.1
rm -f %{buildroot}*/usr/share/man/man1/pdftohtml.1
rm -f %{buildroot}*/usr/share/man/man1/pdftoppm.1
rm -f %{buildroot}*/usr/share/man/man1/pdftops.1
rm -f %{buildroot}*/usr/share/man/man1/pdftotext.1
rm -f %{buildroot}*/usr/share/man/man1/pdfunite.1
## install_append content
rm -v %{buildroot}/usr/lib64/libpoppler-cpp*
rm -v %{buildroot}/usr/lib64/libpoppler-glib*
rm -v %{buildroot}/usr/lib64/libpoppler-qt*
## install_append end

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpoppler.so.123
/usr/lib64/libpoppler.so.123.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-poppler-soname123/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/compat-poppler-soname123/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/compat-poppler-soname123/ff3ed70db4739b3c6747c7f624fe2bad70802987
